### PR TITLE
upgrade to traefik 2.1

### LINKED ISSUE #2: Fix traefik - move to version 2.x
@xamanu How do I setup xamanu/traefik. Docker-compose fails because docker is unable to download this image.

### PR DESCRIPTION
**Pull request by xamanu**
Closes #2

### CODE REVIEW

**Comment by fais3000** [comment]
@xamanu Thanks for working on this. Unfortunately I don't have enough experience with docker to actively contribute but happy test this out for you. 

After this commit I'm getting following error on docker-compose up

`ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 16, column 7
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 28, column 60`

https://stackoverflow.com/questions/38272137/yaml-parser-parsererror-while-parsing-a-block-mapping

**Comment by fais3000** [comment]
@xamanu After formatting the file it starts to compose. Seeing other issues, but formatting error is gone. You can use this file.

```
version: '3.3'
networks:
    web:
        driver: bridge
services:
    reverseproxy:
        image: 'traefik:v2.1'
        restart: unless-stopped
        env_file: .env
        command:
            - '--api.dashboard=true'
            - '--entrypoints.web.address=:80'
            - '--entrypoints.websecure.address=:443'
            - '--providers.docker=true'
            - '--providers.docker.watch=true'
            - '--providers.docker.useBindPortIP=true'
            - '--providers.docker.exposedbydefault=false'
            - '--providers.docker.endpoint=unix:///var/run/docker.sock'
            - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
            - '--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}'
            - '--certificatesresolvers.letsencrypt.acme.domains="${XMPP_GROUPS_URL},${XMPP_HOST_URL}'
            - '--certificatesresolvers.letsencrypt.acme.storage=cert/acme.json'
            - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './data/cert:/cert/'
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.traefik.rule=(Host(`$XMPP_SERVER_URL`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))'
            - traefik.http.routers.traefik.service=api@internal
            - traefik.http.routers.traefik.tls.certresolver=letsencrypt
            - traefik.http.routers.traefik.entrypoints=websecure
            - traefik.http.routers.traefik.middlewares=dashboardauth
            - traefik.http.middlewares.dashboardauth.basicauth.users=$DASHBOARD_HTACCESS
            - 'traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)'
            - traefik.http.routers.http-catchall.entrypoints=web
            - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        networks:
            - web
    xmpp-server:
        image: xamanu/xmpp-prosody
        restart: unless-stopped
        env_file: .env
        volumes:
            - './data/prosody/conf:/etc/prosody/conf.d'
            - './data/cert:/cert/:ro'
            - './data/prosody/data:/var/lib/prosody/data'
        ports:
            - '5222:5222'
            - '5269:5269'
            - '5280:5280'
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.xmpp-server.rule=Host(`$XMPP_SERVER_URL`) && (PathPrefix(`/_xmpp`)'
            - traefik.http.routers.xmpp-server.entrypoints=websecure
            - traefik.http.routers.xmpp-server.tls=true
            - traefik.http.routers.xmpp-server.tls.certresolver=letsencrypt
            - traefik.http.services.xmpp-server.loadbalancer.server.port=5280
        networks:
            - web
    xmpp-filer:
        image: xamanu/xmpp-filer
        restart: unless-stopped
        env_file: .env
        volumes:
            - './data/http-upload:/app/uploads'
        labels:
            - traefik.enable=true
            - 'traefik.http.routers.xmpp-filer.rule=Host(`$XMPP_SERVER_URL`) && (PathPrefix(`/_xmpp/upload`))'
            - traefik.http.routers.xmpp-filer.entrypoints=websecure
            - traefik.http.routers.xmpp-filer.tls=true
            - traefik.http.routers.xmpp-filer.tls.certresolver=letsencrypt
            - traefik.http.services.xmpp-filer.loadbalancer.server.port=5050
        networks:
            - web

**Comment by xamanu** [comment]
Thanks @fais3000. Just applied this and did some tweaks. Now it builds. I'm getting some errors for a few modules. Is this the case on your side, too?

**Comment by fais3000** [comment]
> Thanks @fais3000. Just applied this and did some tweaks. Now it builds. I'm getting some errors for a few modules. Is this the case on your side, too?

Yes, It fails on prosody modules e.g auto_answer_disco_info

I also get certificate errors. but I think that's a separate issue.

**Comment by xamanu** [comment]
I think I was able to just fix the certificate errors. Still looking into the module dependencies.

**Pull request merged**
